// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxkD602cKCJ8K54ib1DYyXf102b6OwaX8',
    appId: '1:298242353025:web:ad848951ef3d07f643aa80',
    messagingSenderId: '298242353025',
    projectId: 'aplikasi-rental-mobil-8ae89',
    authDomain: 'aplikasi-rental-mobil-8ae89.firebaseapp.com',
    storageBucket: 'aplikasi-rental-mobil-8ae89.appspot.com',
    measurementId: 'G-S2FHX2DLHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFkoD-Ixa8H0p5Zm2dgVz99glC7KfrCU',
    appId: '1:298242353025:android:a5f7355f13cabbc643aa80',
    messagingSenderId: '298242353025',
    projectId: 'aplikasi-rental-mobil-8ae89',
    storageBucket: 'aplikasi-rental-mobil-8ae89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8lE71gsDaxVno3Lm2IdFPQwMhFEQ00xA',
    appId: '1:298242353025:ios:3d91be9d752b9f3943aa80',
    messagingSenderId: '298242353025',
    projectId: 'aplikasi-rental-mobil-8ae89',
    storageBucket: 'aplikasi-rental-mobil-8ae89.appspot.com',
    iosBundleId: 'com.example.aplikasiRentalMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8lE71gsDaxVno3Lm2IdFPQwMhFEQ00xA',
    appId: '1:298242353025:ios:3d91be9d752b9f3943aa80',
    messagingSenderId: '298242353025',
    projectId: 'aplikasi-rental-mobil-8ae89',
    storageBucket: 'aplikasi-rental-mobil-8ae89.appspot.com',
    iosBundleId: 'com.example.aplikasiRentalMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxkD602cKCJ8K54ib1DYyXf102b6OwaX8',
    appId: '1:298242353025:web:d778ffd14e312c0143aa80',
    messagingSenderId: '298242353025',
    projectId: 'aplikasi-rental-mobil-8ae89',
    authDomain: 'aplikasi-rental-mobil-8ae89.firebaseapp.com',
    storageBucket: 'aplikasi-rental-mobil-8ae89.appspot.com',
    measurementId: 'G-QHKKM2VYYW',
  );
}
